server:
  port: 8888
spring:
  application:
    name: MYSERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
    # 注册中心地址
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://10.211.109.158:8000/eureka}
    registryFetchIntervalSeconds: 10
    disable-delta: true
